const logoProbe=new Image();logoProbe.onload=()=>{const logo=document.getElementById('brandLogo');if(logo)logo.src='/logo.svg'};logoProbe.src='/logo.svg';
const STORAGE_KEY='natucopos_visual_simulation_v2';
const WHATSAPP='5564999480738';
let currentStep=1;const totalSteps=6;
const choices={segment:['Açaíteria','Sorveteria','Gelateria','Cafeteria','Doceria','Bolo no pote','Restaurante / delivery','Outro'],package_type:['Pote de papel','Copo de papel','Bowl','Combo com mais de uma embalagem'],package_size:['120 ml','240 ml','250 ml','360 ml','500 ml','750 ml','1000 ml'],visual_style:['Premium tropical','Moderno e limpo','Divertido e colorido','Minimalista','Luxo','Natural/sustentável','Fitness','Infantil/divertido']};
const directions={premium:{title:'Opção Premium',short:'Premium',className:'premium-style',description:'Visual mais sofisticado, ideal para marca com posicionamento superior.',focus:'usar linguagem premium, composição elegante, poucos elementos, contraste forte, logo em destaque e visual de marca valorizada.'},colorida:{title:'Opção Colorida',short:'Colorida',className:'colorful-style',description:'Visual mais chamativo, ideal para açaí, sorvete, delivery e redes sociais.',focus:'mais energia visual, frutas, ondas, formas orgânicas, maior presença de cores, comercial e chamativo, sem poluir.'},clean:{title:'Opção Clean',short:'Clean',className:'clean-style',description:'Visual mais limpo, moderno e fácil de aplicar em diferentes embalagens.',focus:'minimalista, fundo claro ou cor sólida, logo central, poucos elementos, elegante e fácil de produzir.'}};
const state={segment:'Açaíteria',package_type:'Pote de papel',package_size:'750 ml',visual_style:'Premium tropical',prompts:{},selected_direction:'',requested_adjustment:''};
const form=document.getElementById('simulationForm');
function initChoices(){document.querySelectorAll('[data-name]').forEach(box=>{const name=box.dataset.name;box.innerHTML='';choices[name].forEach(v=>{const b=document.createElement('button');b.type='button';b.className=(name==='package_size'?'chip':'option')+(state[name]===v?' selected':'');b.textContent=v;b.onclick=()=>{state[name]=v;box.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');save();updateMainPreview();};box.appendChild(b);});});}
function formData(){const d=Object.fromEntries(new FormData(form).entries());Object.assign(d,state);const file=form.logo_file.files[0];d.logo_file_name=file?file.name:(d.logo_file_name||'');d.has_logo=!!file&&!form.no_logo.checked;d.wants_qr_code=d.wants_qr_code||'Não';return d;}
function utms(){const p=new URLSearchParams(location.search);return{utm_source:p.get('utm_source')||'',utm_campaign:p.get('utm_campaign')||'',utm_medium:p.get('utm_medium')||'',utm_content:p.get('utm_content')||'',utm_term:p.get('utm_term')||''};}
function fixedRules(){return ['não criar mockup 3D','criar arte plana frontal 1:1','não inventar marca','não copiar textos de imagens de referência','não criar tampa','não alterar formato real da embalagem','não escrever textos pequenos ilegíveis','reservar área limpa para logo','usar somente dados enviados pelo cliente'];}
function makePrompt(d,key='base'){const dir=directions[key];const focus=dir?dir.focus:`respeitar o estilo solicitado: ${d.visual_style||''}.`;return `Crie uma arte plana frontal 1:1 para embalagem personalizada Natucopos.\n\nDireção visual: ${dir?dir.title:d.visual_style||'Briefing técnico'}\nObjetivo: ${focus}\nMarca informada pelo cliente: ${d.company_name||''}\nSegmento: ${d.segment||''}\nProduto: ${d.product_description||''}\nEmbalagem real: ${d.package_type||''} ${d.package_size||''}\nCores enviadas: principal ${d.primary_color||''}, secundária ${d.secondary_color||''}, apoio ${d.support_color||''}\nFrase principal: ${d.main_phrase||''}\nFrase secundária: ${d.secondary_phrase||''}\nInstagram: ${d.package_instagram||d.instagram||''}\nWhatsApp/telefone: ${d.package_phone||''}\nObservações do cliente: ${d.observations||''}\nLogo: ${d.has_logo?'cliente enviou arquivo '+d.logo_file_name:'cliente não enviou logo; reservar área limpa para aplicação posterior'}\n\nRegras fixas obrigatórias:\n- ${fixedRules().join('\n- ')}\n\nResultado esperado: composição comercial profissional, aplicável na frente da embalagem, com leitura clara e sem elementos que dificultem produção.`;}
function buildPrompts(){const d=formData();state.prompts={premium:makePrompt(d,'premium'),colorida:makePrompt(d,'colorida'),clean:makePrompt(d,'clean')};return state.prompts;}
function visualSimulationPayload(){const d=formData();return{simulation_id:state.simulation_id||(state.simulation_id=`NATU-${Date.now()}`),created_at:state.created_at||(state.created_at=new Date().toISOString()),source:'simulador_natucopos_v2',utms:utms(),customer:{name:d.customer_name||'',whatsapp:d.whatsapp||'',city_state:d.city_state||'',instagram:d.instagram||''},package:{type:d.package_type||'',size:d.package_size||''},brand:{name:d.company_name||'',main_phrase:d.main_phrase||'',secondary_phrase:d.secondary_phrase||'',package_instagram:d.package_instagram||'',package_phone:d.package_phone||'',colors:{primary:d.primary_color||'',secondary:d.secondary_color||'',support:d.support_color||''}},briefing:{segment:d.segment||'',product_description:d.product_description||'',visual_style:d.visual_style||'',observations:d.observations||'',wants_qr_code:d.wants_qr_code==='Sim',qr_code_url:d.qr_code_url||''},prompts:state.prompts,selected_direction:state.selected_direction,requested_adjustment:state.requested_adjustment,logo_file_name:d.logo_file_name||'',status:'visual_direction_selected'};}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({...formData(),...state}));}
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');Object.assign(state,{segment:s.segment||state.segment,package_type:s.package_type||state.package_type,package_size:s.package_size||state.package_size,visual_style:s.visual_style||state.visual_style,prompts:s.prompts||{},selected_direction:s.selected_direction||'',requested_adjustment:s.requested_adjustment||'',simulation_id:s.simulation_id,created_at:s.created_at});Object.entries(s).forEach(([k,v])=>{const el=form.elements[k];if(!el)return;if(el.type==='checkbox')el.checked=!!v;else if(el.type!=='file')el.value=v;});}catch(e){}}
function validate(){if(currentStep!==1)return true;let ok=true;['customer_name','whatsapp','company_name'].forEach(n=>{const el=form.elements[n];el.classList.toggle('error',!el.value.trim());if(!el.value.trim())ok=false;});return ok;}
function showStep(n){currentStep=n;document.querySelectorAll('.step').forEach(s=>s.classList.toggle('active',+s.dataset.step===n));document.getElementById('prevBtn').style.display=n===1?'none':'inline-flex';document.getElementById('nextBtn').textContent=n===5?'Finalizar briefing':'Continuar';document.querySelector('.form-actions').style.display=n===6?'none':'flex';const pct=Math.round(n/totalSteps*100);document.getElementById('stepLabel').textContent=`Etapa ${n} de ${totalSteps}`;document.getElementById('progressPercent').textContent=`${pct}%`;document.getElementById('progressBar').style.width=`${pct}%`;if(n===6)renderResult();save();}
function renderResult(){buildPrompts();const p=visualSimulationPayload();window.visualSimulationPayload=p;document.getElementById('summary').innerHTML=`<div><b>Cliente:</b> ${p.customer.name} • ${p.customer.whatsapp}</div><div><b>Marca:</b> ${p.brand.name} • ${p.customer.city_state}</div><div><b>Embalagem:</b> ${p.package.type} ${p.package.size}</div><div><b>Estilo inicial:</b> ${p.briefing.visual_style}</div><div><b>Cores:</b> ${p.brand.colors.primary}, ${p.brand.colors.secondary}, ${p.brand.colors.support}</div><div><b>Textos:</b> ${p.brand.main_phrase} ${p.brand.secondary_phrase}</div><div><b>Logo:</b> ${p.logo_file_name||'Sem arquivo enviado'}</div>`;document.getElementById('generatedPrompt').textContent=makePrompt(formData(),'base');updateMainPreview();if(!document.getElementById('simulationOptions').hidden)renderOptions();updateChosen();save();}
function mockupHtml(key){const d=formData();return `<div class="visual-mockup ${directions[key].className}" style="--primary:${d.primary_color||'#0f7a3b'};--secondary:${d.secondary_color||'#f3c96b'};--support:${d.support_color||'#ffffff'}"><div class="mock-shape"><strong>${d.company_name||'Sua marca'}</strong><span>${d.main_phrase||directions[key].short}</span><small>${d.package_instagram||d.instagram||'@instagram'}</small></div></div>`;}
function updateMainPreview(){const el=document.getElementById('mainPreview');if(el)el.outerHTML=mockupHtml(state.selected_direction||'premium').replace('visual-mockup','visual-mockup').replace('<div class="visual-mockup','<div id="mainPreview" class="visual-mockup');}
function renderOptions(){const wrap=document.getElementById('simulationOptions');wrap.hidden=false;wrap.innerHTML=Object.entries(directions).map(([key,dir])=>`<article class="simulation-card ${state.selected_direction===key?'selected':''}" data-card="${key}"><span class="status">${state.selected_direction===key?'Selecionado':'Pronto para gerar'}</span><h3>${dir.title}</h3><p>${dir.description}</p>${mockupHtml(key)}<div class="prompt-mini"><pre>${state.prompts[key]||makePrompt(formData(),key)}</pre><button type="button" data-copy="${key}">Copiar prompt</button></div><div class="card-actions"><button class="btn primary" type="button" data-select="${key}">Selecionar essa direção</button><button class="btn ghost" type="button" data-adjust="${key}">Pedir ajuste</button></div><div class="adjust-box ${state.selected_direction===key&&state.requested_adjustment?'open':''}" data-adjust-box="${key}"><label>Descreva o que quer mudar<textarea data-adjust-text="${key}" placeholder="Ex: deixar mais premium, trocar cor, aumentar logo, tirar elementos tropicais, deixar mais moderno">${state.selected_direction===key?state.requested_adjustment:''}</textarea></label></div></article>`).join('');}
function updateChosen(){const box=document.getElementById('chosenDirection');const btn=document.getElementById('sendSimulation');if(state.selected_direction){box.hidden=false;box.textContent=`Direção escolhida: ${directions[state.selected_direction].title}${state.requested_adjustment?' • Ajuste solicitado: '+state.requested_adjustment:''}`;btn.disabled=false;}else{box.hidden=true;btn.disabled=true;}window.visualSimulationPayload=visualSimulationPayload();}
function whatsUrl(){const p=visualSimulationPayload();const dir=directions[p.selected_direction];const msg=`Olá, quero enviar minha simulação Natucopos V2 para atendimento.\n\nDados do cliente:\nNome: ${p.customer.name}\nWhatsApp: ${p.customer.whatsapp}\nCidade/Estado: ${p.customer.city_state}\nInstagram: ${p.customer.instagram}\n\nEmbalagem: ${p.package.type}\nTamanho: ${p.package.size}\nMarca: ${p.brand.name}\nEstilo escolhido: ${p.briefing.visual_style}\nDireção visual escolhida: ${dir?dir.title:''}\nAjuste solicitado: ${p.requested_adjustment||'Nenhum'}\n\nPrompt técnico da direção escolhida:\n${p.prompts[p.selected_direction]||''}\n\nAviso: esta é uma simulação e não é arte final. A arte final passa por conferência humana antes da produção.`;return`https://api.whatsapp.com/send?phone=${WHATSAPP}&text=${encodeURIComponent(msg)}`;}
load();initChoices();showStep(1);updateMainPreview();
form.addEventListener('input',e=>{if(e.target.matches('[data-adjust-text]')){state.selected_direction=e.target.dataset.adjustText;state.requested_adjustment=e.target.value;updateChosen();}save();updateMainPreview();});
document.getElementById('nextBtn').onclick=()=>{if(!validate())return;if(currentStep<6)showStep(currentStep+1);};
document.getElementById('prevBtn').onclick=()=>showStep(currentStep-1);
document.getElementById('clearSimulation').onclick=()=>{localStorage.removeItem(STORAGE_KEY);location.reload();};
document.getElementById('copyPrompt').onclick=()=>navigator.clipboard.writeText(document.getElementById('generatedPrompt').textContent);
document.getElementById('generateOptions').onclick=()=>{buildPrompts();renderOptions();save();};
document.getElementById('simulationOptions').addEventListener('click',e=>{const copy=e.target.closest('[data-copy]');const select=e.target.closest('[data-select]');const adjust=e.target.closest('[data-adjust]');if(copy){navigator.clipboard.writeText(state.prompts[copy.dataset.copy]||makePrompt(formData(),copy.dataset.copy));}if(select){state.selected_direction=select.dataset.select;renderOptions();updateChosen();save();}if(adjust){const key=adjust.dataset.adjust;state.selected_direction=key;renderOptions();const box=document.querySelector(`[data-adjust-box="${key}"]`);box.classList.add('open');box.querySelector('textarea').focus();updateChosen();save();}});
document.getElementById('sendSimulation').onclick=()=>{if(!state.selected_direction)return;window.open(whatsUrl(),'_blank','noopener');};
document.getElementById('startSimulation').onclick=()=>setTimeout(()=>form.elements.customer_name.focus(),450);
